version: '2.3'

services:

  tex2shape:
    image: tex2shape
    container_name: tex2shape
    working_dir: /tex2shape
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - PYTHONPATH=/tex2shape
    volumes:
      - ../:/tex2shape
    runtime: nvidia
    command: bash /setup.sh

  densepose:
    image: densepose
    container_name: densepose
    working_dir: /detectron2_repo/projects/DensePose
    build:
      context: ../
      dockerfile: docker/Dockerfile.densepose
    volumes:
      - ../:/densepose
    runtime: nvidia
    command: tail /dev/null -f

# python3 apply_net.py show /detectron2_repo/projects/DensePose/configs/densepose_rcnn_R_50_FPN_s1x.yaml /detectron2_repo/projects/DensePose/model_final_dd99d2.pkl /densepose/data/images/spotlight_001.jpg dp_contour,bbox --output /densepose/out/image_densepose_contour.png